### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by BJNFNE** [bennytrt/Sharpstation#2]
Hi, where is the Soure code of the Project?
could you maybe add it to the repository?

**Comment by bennytrt** [comment]
Hey! Sorry For The Late Reply! Im Currently Rewriting And Redoing The WHOLE Project, As I Lost The Original Source Code I Originally Wrote When I Made This Repo, I Will Upload The Source Code Later On When I Have More Progress Instead Of Just ROM Loading ! :)

**Comment by bennytrt** [comment]
Hi There! I Uploaded The Source Like I Said I Would, I Couldn't Wait To Upload It Because I Would've Forgotten it.
